### ISSUE TITLE
Medium渐进式图片加载方式探究

### ISSUE THREAD

**Issue by ccyongzhi** [ccyongzhi/the-Learned#14]
最近看到了一篇文章( [链接](https://jmperezperez.com/medium-image-progressive-loading-placeholder/) )，讲的是国外博客网站Medium是如何实现文章中的图片平滑加载的。
<video controls="" style="max-width:100%" width="854" height="400"><source src="https://jmperezperez.com/assets/images/posts/medium-progressive-loading.mp4" type="video/mp4"></video>

其原理并不复杂，代码如下。HTML中图片的默认地址是一张小图，页面载入后，首先加载小图，并通过设置CSS属性
```css
filter: blur(50px);
```
来使图片达到模糊效果。大图加载完毕后，将大图添加到placeholder中，因为img的CSS属性
```
position: absolute;
top: 0;
left: 0;
transition: opacity 1s linear;
```
大图将小图覆盖，并且实现了平滑过渡。

整体代码如下(转载自 [链接](http://codepen.io/jmperez/pen/yYjPER) )

###### HTML代码
```html
<div class="placeholder" data-large="https://cdn-images-1.medium.com/max/1800/1*sg-uLNm73whmdOgKlrQdZA.jpeg">
	<img src="https://cdn-images-1.medium.com/freeze/max/27/1*sg-uLNm73whmdOgKlrQdZA.jpeg?q=20" class="img-small">
	<div style="padding-bottom: 66.6%;"></div>
</div>
```
###### JavaScript代码
```javascript
window.onload = function() {
	var placeholder = document.querySelector('.placeholder'),
	var small = placeholder.querySelector('.img-small')
  
	// 首先加载小图
	var img = new Image();
	img.src = small.src;
	img.onload = function () {
		//加载完成后，改变opacity，显示图片
		small.classList.add('loaded');
	};
	  
	var imgLarge = new Image();
	// 从图片的data-large属性中获取大图地址
	imgLarge.src = placeholder.dataset.large; 
	imgLarge.onload = function () {
		//加载完成后，改变opacity，显示图片
		imgLarge.classList.add('loaded');
	};
	placeholder.appendChild(imgLarge);
}
```
###### CSS代码
```css
.placeholder {
  background-color: #f6f6f6;
  background-size: cover;
  background-repeat: no-repeat;
  position: relative;
  overflow: hidden;
}

.placeholder img {
  position: absolute;
  opacity: 0;
  top: 0;
  left: 0;
  width: 100%;
  transition: opacity 1s linear;
}
	
.placeholder img.loaded {
  opacity: 1;
}
	
.img-small {
  filter: blur(50px);
  transform: scale(1);
}
```

在这个例子中，小图体积为696字节，大图体积为313043字节。打开Chrome开发者工具，勾选"Disable cache"以消除浏览器缓存的影响，在我自己家里的网络中，通过控制台可以看到，小图加载时间为164m,而大图为3.01s，差距十分明显，因此这种显示图片的方式可以明显改善用户体验。

![小图下载时间](http://of78v3am8.bkt.clouddn.com/2016-10-19-21%3A49%3A08.jpg)

![大图下载时间](http://of78v3am8.bkt.clouddn.com/2016-10-19-21%3A50%3A22.jpg)
