### ISSUE TITLE
CSS实现垂直居中的方法

### ISSUE THREAD

**Issue by ccyongzhi** [ccyongzhi/the-Learned#21]
实现垂直居中，有如下方式

 一. 块级元素
(1) 利用margin:auto实现
```html
<div class="outer-div01 d-ib">
  <div class="inner-div01">
    <span>已定宽高</span>
    <br>
    <span>利用margin:auto实现</span>
  </div>
</div>
```

```css
.outer-div01 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
  position: relative;
}

.inner-div01 {
  background-color: #00ff00;
  height: 100px;
  width: 200px;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
}
```

(2) 利用position:absolute; top, left, margin实现
```html
<div class="outer-div02 d-ib">
  <div class="inner-div02">
    <span>已定宽高</span>
    <br>
    <span>利用position:absolute; top, left, margin实现</span>
  </div>
</div>
```

```css
.outer-div02 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
  position: relative;
}

.inner-div02 {
  background-color: #00ff00;
  height: 100px;
  width: 200px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left: -100px;
  margin-top: -50px;
}
```

(3) 利用transform: translate()实现
```html
<div class="outer-div03 d-ib">
  <div class="inner-div03">
    <span>宽高定不定均可</span>
    <br>
    <span>利用transform: translate()实现</span>
  </div>
</div>
```

```css
.outer-div03 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
  position: relative;
}

.inner-div03 {
  background-color: #00ff00;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

(4) 利用display:table-cell实现
```html
<div class="outer-div04">
  <div class="inner-div04">
    <span>宽高定不定均可</span>
    <br>
    <span>利用display:table-cell实现</span>
  </div>
</div>
```

```css
.outer-div04 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
  display: table-cell;
  vertical-align: middle;
  text-align: center;
  position: relative;
}
.inner-div04 {
  background-color: #00ff00;
  display: inline-block;
}
```

(5) 利用flexbox实现
```html
<div class="outer-div05 d-ib">
  <div class="inner-div05">
    <span>宽高定不定均可</span>
    <br>
    <span>利用flexbox实现</span>
  </div>
</div>
```

```css
.outer-div05 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 10px;
}
.inner-div05 {
  background-color: #00ff00;
  height: 100px;
  width: 200px;
}
```

代码已经放到了codepen上，点击下面这个链接可以查看实际效果
[元素居中测试 - 块级元素](http://codepen.io/CodingPenny/pen/wgLEpQ)

二. 内联元素
(1) 设置line-height等于父元素高度实现垂直居中
```html
<div class="outer-div01">
  <span class="inner-span01">通过line-height实现垂直居中</span>
</div>
```

```css
.outer-div01 {
  height: 200px;
  width: 300px;
  background-color: #ff0000;
}

.inner-span01 {
  background-color: #00ff00;
  font-size: 20px;
  line-height: 200px;
}
```

(2) 设置 display:table-cell 实现垂直居中
```html
<div class="outer-div02">
  <span class="inner-span02">通过设置display:table-cell实现垂直居中</span>
</div>
```

```css
.outer-div02 {
  height: 200px;
  width: 300px;
  background-color: #ff00ff;
  margin-top: 10px;
  display: table-cell;
  vertical-align: middle;
}

.inner-span02 {
  background-color: #00ff00;
}
```

代码已经放到了codepen上，点击下面这个链接可以查看实际效果
[元素居中测试 - 内联元素](http://codepen.io/CodingPenny/pen/zNVmGz)
