### ISSUE TITLE
Less 中变量数值与单位相加产生多余空格的问题

### ISSUE THREAD

**Issue by ccyongzhi** [ccyongzhi/the-Learned#28]
今天在一个项目中引入了 Less，遇到了一个问题，
```less
.generate-init-pos(3);
.generate-init-pos(@n, @i: 1) when (@i <= @n) {
  .cls1.nth-child(@{i}) {
    transition-delay: 0.02 * @i + s;
    transform: rotate( 45 + @i * 40 + deg );
  }
  .generate-init-pos(@n, @i + 1);
}
```
以上代码生成的 CSS 如下
```css
.cls1.nth-child(1) {
  transition-delay: 0.02 s;
  transform: rotate(85 deg);
}
.cls1.nth-child(2) {
  transition-delay: 0.04 s;
  transform: rotate(125 deg);
}
.cls1.nth-child(3) {
  transition-delay: 0.06 s;
  transform: rotate(165 deg);
}
```
s 和 deg 之前都多了一个空格，导致 CSS 失效。为此我想了很久，结合万能的谷歌，终于找到了解决方法：
使用 unit 函数
```less
.generate-init-pos(3);
.generate-init-pos(@n, @i: 1) when (@i <= @n) {
  .cls1.nth-child(@{i}) {
    transition-delay: unit(0.02 * @i, s);
    transform: rotate( unit(45 + @i * 40, deg) );
  }
  .generate-init-pos(@n, @i + 1);
}
```
生成的 CSS 如下，空格就没有了
```css
.cls1.nth-child(1) {
  transition-delay: 0.02s;
  transform: rotate(85deg);
}
.cls1.nth-child(2) {
  transition-delay: 0.04s;
  transform: rotate(125deg);
}
.cls1.nth-child(3) {
  transition-delay: 0.06s;
  transform: rotate(165deg);
}
```
